Feature/implement java agent messages bufferization during admin unavailabiity epmdj 10741
Drill4J/java-agent pull request #134
Opened 2023-12-22 12:05 UTC by epamrsa

2024-01-24 16:42 UTC, RomanDavlyatshin requested changes

2024-01-30 14:07 UTC, RomanDavlyatshin commented
Converting to draft bc `feature/implement-java-agent-messages-bufferization-during-admin-unavailabiity-EPMDJ-107411` is already merged in #138 
This PR is kept around to preserve TODO comments

2024-01-31 14:53 UTC, RomanDavlyatshin commented
already merged at https://github.com/Drill4J/java-agent/pull/138

2024-02-01 10:15 UTC, epamrsa commented on test2code/src/main/kotlin/com/epam/drill/test2code/Test2Code.kt
> +        logger.debug { "sendClassMetadata: Sending class metadata: $message" }
I think in this case dubug is optimal, as this event occurred only once per agent launch. TRACE is typically used for frequently repeated messages, like send coverage data.

2024-02-01 10:16 UTC, epamrsa commented on test2code/src/main/kotlin/com/epam/drill/test2code/Test2Code.kt
> +        logger.debug { "sendClassMetadataComplete: Sending class metadata complete message" }
I think in this case dubug is optimal, as this event occurred only once per agent launch. TRACE is typically used for frequently repeated messages, like send coverage data.

2024-02-01 10:19 UTC, epamrsa commented on test2code/src/main/kotlin/com/epam/drill/test2code/Test2Code.kt
> +                .also(::sendClassMetadata)
Just matter of code style, the pair of sendClassMetadata and sendClassMetadataComplete methods looks logical and understandable.

2024-02-13 11:11 UTC, closed without merging